name: "amqp-test"
on:
  push:
    branches:
      - master
      - "*_cow"
    tags:
      - release*  
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['1.8','1.9','2.0','2.1']

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      # Force SSH authentication for repositories with HTTPS references
      - name: Git Config
        run: |
          git config --global --add url.ssh://git@github.com/flexera/.insteadof https://github.com/flexera/
          git config --global --add url.ssh://git@github.com/rightscale/.insteadof https://github.com/rightscale/
      
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Run Spec
        run: bundle exec rake ci:spec